name: "Create a UnityPackage"
description: "Create a UnityPackage from Meta"
inputs:
  meta:
    required: false
    description: "meta collections"
  package:
    required: false
    description: "package.json for packaging"
  packages:
    required: false
    description: "array of package.json for packaging"
  root:
    required: false
    description: "root directory"
  output:
    required: false
    description: "output filename"
  outputs:
    required: false
    description: "array of output filename"
runs:
  using: "node16"
  main: "dist/index.js"
