name: "Create a UnityPackage"
description: "Create a UnityPackage on GitHub Actions, without Unity Editor"
inputs:
  root:
    required: false
    description: "the Unity project root directory"
  files:
    required: false
    description: "the actual file paths (not meta) to include to unitypackage"
  files-glob:
    required: false
    description: "the glob patterns for actual file paths (not meta) to include to unitypackage"
  dest:
    required: true
    description: "the destination path for creating unitypackage"
runs:
  using: "node20"
  main: "dist/index.js"
