on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # example action for packaging ./fixtures/Assets/MonoBehaviourAsset.cs only
      # extracted:
      #   MonoBehaviourAsset.cs
      - name: with files (root)
        uses: ./
        with:
          root: ./fixtures/
          files: |
            ./fixtures/Assets/MonoBehaviourAsset.cs
          dest: dist/test1.unitypackage

      # example action for packaging all C# script files
      # extracted:
      #  FolderAsset/
      #  ├─ OtherMonoBehaviourAsset.cs
      #  MonoBehaviourAsset.cs
      - name: with files-glob (without gitignore)
        uses: ./
        with:
          root: ./fixtures
          files-glob: |
            ./fixtures/**/*.cs
          dest: dist/test2.unitypackage

      - name: write .gitignore
        run: |
          echo "**/*.cs" >> ./fixtures/.gitignore

      # example action for packaging all files, but respect .gitignore
      # extracted:
      #   FolderAsset/
      #   ├─ Shaders.txt
      - name: with files-glob (with gitignore)
        uses: ./
        with:
          root: ./fixtures
          files-glob: |
            ./fixtures/**/*
          dest: dist/test3.unitypackage

      # example action for packaging all files, but **not** respect .gitignore
      # extracted:
      #   FolderAsset/
      #   ├─ Shaders.txt
      #   ├─ OtherMonoBehaviourAsset.cs
      #   MonoBehaviourAsset.cs
      - name: with files-glob (not respect gitignore)
        uses: ./
        with:
          root: ./fixtures
          files-glob: |
            ./fixtures/**/*
          respect-gitignore: false
          dest: dist/test4.unitypackage

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.unitypackage
